apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./k8s/**/*
build:
  local:
    push: false
  artifacts:
    - image: csup96/tour-auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: csup96/tour-booking
      context: booking
      docker:
        dockerfile: Dockerfile
    - image: csup96/tour-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
    - image: csup96/tour-review
      context: review
      docker:
        dockerfile: Dockerfile
    - image: csup96/tour-tour
      context: tour
      docker:
        dockerfile: Dockerfile
