apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: csup96/tour-auth
          env:
            - name: NODE_ENV
              value: 'development'
            - name: PORT
              value: '3000'
            - name: MONGO_URI
              value: 'mongodb://auth-mongo:27017/auth'
            - name: COOKIE_ACCESS_EXPIRATION
              value: '1'
            - name: COOKIE_REFRESH_EXPIRATION
              value: '30'
            - name: JWT_ACCESS_SECRET
              value: 'personal-tour-project-in-nodejs-typescript-access'
            - name: JWT_REFRESH_SECRET
              value: 'personal-tour-project-in-nodejs-typescript-refresh'
            - name: NODEMAILER_HOST
              value: 'sandbox.smtp.mailtrap.io'
            - name: NODEMAILER_PORT
              value: '2525'
            - name: NODEMAILER_USER
              value: 'c3518266542222'
            - name: NODEMAILER_PASS
              value: '7eac6749a5738c'
            - name: NATS_URL
              value: 'http://nats:4222'
            - name: NATS_CLUSTER_ID
              value: tour
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
