apiVersion: v1
kind: Service
metadata:
  name: tour-mongo
spec:
  selector:
    app: tour-mongo
  ports:
    - name: tour-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
