apiVersion: v1
kind: Service
metadata:
  name: review-mongo
spec:
  selector:
    app: review-mongo
  ports:
    - name: review-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
