apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-redis
  template:
    metadata:
      labels:
        app: payment-redis
    spec:
      containers:
        - name: payment-redis
          image: redis:7.2.4
