apiVersion: v1
kind: Service
metadata:
  name: payment-redis
spec:
  selector:
    app: payment-redis
  ports:
    - name: payment-redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
