apiVersion: v1
kind: Service
metadata:
  name: payment-mongo
spec:
  selector:
    app: payment-mongo
  ports:
    - name: payment-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
