apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tour-redis
  template:
    metadata:
      labels:
        app: tour-redis
    spec:
      containers:
        - name: tour-redis
          image: redis:7.2.4
