apiVersion: v1
kind: Service
metadata:
  name: booking-redis
spec:
  selector:
    app: booking-redis
  ports:
    - name: booking-redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
