apiVersion: v1
kind: Service
metadata:
  name: auth-redis
spec:
  selector:
    app: auth-redis
  ports:
    - name: auth-redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
