apiVersion: v1
kind: Service
metadata:
  name: booking-mongo
spec:
  selector:
    app: booking-mongo
  ports:
    - name: booking-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
