apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: csup96/tour-booking
          env:
            - name: NODE_ENV
              value: 'development'
            - name: PORT
              value: '3000'
            - name: MONGO_URI
              value: 'mongodb://booking-mongo:27017/booking'
            - name: REDIS_HOST
              value: 'booking-redis'
            - name: REDIS_PORT
              value: '6379'
            - name: JWT_ACCESS_SECRET
              value: 'personal-tour-project-in-nodejs-typescript-access'
            - name: JWT_REFRESH_SECRET
              value: 'personal-tour-project-in-nodejs-typescript-refresh'
            - name: EXPIRATION_WINDOW
              value: '60'
            - name: NATS_URL
              value: 'http://nats:4222'
            - name: NATS_CLUSTER_ID
              value: 'tour'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
